### ISSUE TITLE
LocalTime

### ISSUE THREAD

**Issue by wimmelstein** [dnieuwenhuizen97/Opdrachten_Java_Advanced#1]
Hoi Dylan.

Ziet er goed uit. Alleen is LocalTime geen tijdsduur, maar echt een tijdstip. LocalTime.of(0, 57, 13) betekent dus 57 minuten een 13 seconden na 12. Als je een duur wilt weergeven, zou ik eens kijken naar Duration en naar formatting als het gaat om het representeren daarvan.

`import java.time.Duration;

public class Main {

    public static void main(String[] args) {
        System.out.println(Duration.ofHours(1L).plus(Duration.ofMinutes(20).plus(Duration.ofSeconds(20))));
    }
}`

Output:
`PT1H20M20S`
Met vriendelijke groet,
Wim Wiltenburg

**Comment by dnieuwenhuizen97** [comment]
Bedankt voor de feedback! ik ga hier nog even mee aan de slag

**Comment by dnieuwenhuizen97** [comment]
Hoi Wim,

Ik heb de LocalTime aangepast naar Duration. Alleen krijg ik nu bij het runnen het volgende probleem: 

Web server failed to start. Port 8080 was already in use.

Action:

Identify and stop the process that's listening on port 8080 or configure this application to listen on another port.

Weet u hoe ik het lopende proces kan stoppen zodat ik het opnieuw kan runnen?

Met vriendelijke groet,
Dylan

**Comment by wimmelstein** [comment]
Blijkbaar heb je al een instance van de api draaiend. Misschien heb je een tweede window met IntelliJ open. As dat niet het geval is, dan kun je in taakbeheer kijken of er een Java of openjdk binary hebt draaien. Als dat het geval is kun je deze beëindigen en het nog eens proberen...

**Comment by wimmelstein** [comment]
Heb je je changes gepusht? Ik zie de changes niet

**Comment by dnieuwenhuizen97** [comment]
Bedankt! het zou nu moeten werken. Changes zijn nu gepusht

**Comment by wimmelstein** [comment]
Inderdaad. Je moet je wel voorstellen dat je vanuit een formulier in een HTML pagina een nieuwe CD moet kunnen maken en het veld voor duration is dan een string, bijvoorbeeld “00:03:59”. Je kunt je voorstellen dat je dat veld moet valideren en parsen naar een Duration. Je hebt het jezelf niet makkelijk gemaakt 😀

**Comment by wimmelstein** [comment]
Misschien is het dan een goed idee om alvast een method te maken die van een string een duration maakt en een die andersom gaat. Deze kun je dan vanuit je constructor aanroepen, bijv. 
private createDurationFromString(String input)
{
  String hours = input.split(“:”)[0];
  /*
     insert code
 */
  return Duration.of( // creation code)
